#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);
use File::Path;

# create
event_actions('vhost-create', qw(
	     nethserver-vhosts-set-permissions 20
             nethserver-virtualhosts-setbasicpassword 30
));

# modify
event_actions('vhost-modify', qw(
	     nethserver-vhosts-set-permissions 20
             nethserver-virtualhosts-setbasicpassword 30
));

# delete
event_actions('vhost-delete', qw(
	     nethserver-vhosts-delete 15
             nethserver-virtualhosts-setbasicpassword 30
));


#--------------------------------------------------
# actions for nethserver-virtualhosts-update event
#--------------------------------------------------

my $event = 'nethserver-virtualhosts-update';

event_actions($event, qw(
	     initialize-default-databases 00
             nethserver-virtualhosts-setbasicpassword 40
));

event_templates('nethserver-httpd-update', qw(
                /etc/httpd/conf.d/virtualhosts.conf
));


#--------------------------------------------------
# actions for nethserver-virtualhosts-save event
#--------------------------------------------------

$event = 'nethserver-virtualhosts-save';

event_actions($event, qw(
             initialize-default-databases 00
));

event_templates($event, qw(
                /etc/httpd/conf.d/virtualhosts.conf
                /etc/vsftpd/user_list
));

event_services($event, qw(
               httpd restart
               vsftpd restart
));


#--------------------------------------------------
# actions for vhost-name validator
#--------------------------------------------------
validator_actions('vhost-create', qw(
                  uniq-vhost 20
));



